---
title: "extract_covariates"
author: "Aimara Planillo"
date: "2023-12-18"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Extract environmental covariates


```{r}
source("./rscripts/source_packages.R")
```

### Load data
```{r}
## bird grid data
birds_grid <- st_read("./data/berlin_grid1x1km_3035.gpkg")

### load bird locations
birds_locations <- st_read("./data/bird_territories_3035.gpkg")
head(birds_locations)
length(unique(birds_locations$sp_name)) # 97 number of species
length(unique(birds_locations$transect)) # 30 number of transects
length(unique(birds_locations$unique_ter_id)) # 7151 number of territories


## berlin border to plot
berlin <- read_sf("./data/geodata/Berlin_border_3035.gpkg", crs =3035)
plot(st_geometry(berlin))
plot(st_geometry(birds_grid), add = TRUE, border = "blue")

ggplot(data = berlin) + 
  geom_sf(fill = "antiquewhite") +
  geom_sf(data = birds_grid, fill = "blue")

## environmental layers
# impervious surface 
imperv <-rast("./data/geodata/IMD_cropped_Berlin.tif")
imperv
# plot(imperv)

# human population density
pop_den <- rast("./data/geodata/human_population_density_raster_10m_2017_3035.tif")

# tree cover
tcd <- rast("./data/geodata/tree_cover_density_raster_10m_2018_3035.tif")

# light polution
light <- rast("./data/geodata/light_pollution_raster_10m_2017_3035.tif")

# noise
noise <- rast("./data/geodata/noise_berlin_raster_10m_2017_3035.tif")

## spectral analysis data
glcm_rast <- rast("./data/geodata/RE_pca_ndvi_glcm.tif")
raster_names <- read.csv("./data/geodata/RE_pca_ndvi_glcm_names.csv")
names(glcm_rast) <- raster_names$names
glcm_rast
```


### Stack all enviromental rasters

set all variables to the same extent
```{r}
imperv <- project(imperv, pop_den)

urban_variables <- c(imperv, pop_den, tcd, light, noise)
names(urban_variables) <- c("imperv", "pop_den", "tcd", "light", "noise")

veg_variables <- c(glcm_rast$PC1, glcm_rast$PC2, glcm_rast$ndvi, glcm_rast$glcm_mean, glcm_rast$glcm_homogeneity)
names(veg_variables) <- c("veg_pca1", "veg_pca2", "ndvi", "glcm", "glcm_hmg")

```


```{r}
plot(veg_variables$glcm_homogeneity, colNA = "black")

plot(glcm_rast$glcm_homogeneity, colNA = "black")
plot(birds_grid, add = TRUE, border = "red", col = "transparent")

allenv_quadrants <- cbind(env_quadrants, veg_quad)
```

## extract environmental variables grid scale

```{r}
mean_urban_grid <- terra::extract(urban_variables, birds_grid, fun = mean, na.rm = TRUE)
head(mean_urban_grid)

mean_veg_grid <- terra::extract(veg_variables, birds_grid, fun = mean, na.rm = TRUE)
head(mean_veg_grid)

birds_grid_var <- cbind(birds_grid, mean_urban_grid, mean_veg_grid) %>% 
  dplyr::select(-ID, -ID.1)

summary(birds_grid_var)

tmap_mode("view")
tm_shape(urban_variables) +
  tm_raster("imperv") +
  tm_shape(birds_grid_var) +
  tm_polygons("imperv", alpha = 0.5, border.col = "black")

grid_variables <- birds_grid_var %>% 
  st_drop_geometry()

# write.csv(grid_variables, "./data/grids_environmental_variables.csv", row.names = FALSE)
```


## extract environmental variables territory scale

### get territories
remove incomplete data and get a table with the centroids
```{r}
data_centroids <- birds_locations %>% 
  filter(transect != "be1") %>%  ## we remove transect 1 because it was incomplete
  filter(!sp_name %in% c("Apus apus", "Passer domesticus")) %>% # these species do not have reliable data
  group_by(unique_ter_id) %>% 
  summarise() %>%
  st_centroid()
nrow(data_centroids) # total number of territories after filtering
# [1] 6515
```

add centroids to data
```{r}
## add info of the territories to the centroids
data_terr_tojoin <- birds_locations %>% 
  st_drop_geometry() %>% 
  filter(transect != "be1") %>%  ## we remove transect 1 because it was incomplete
  filter(!sp_name %in% c("Apus apus", "Passer domesticus")) %>% # these species do not have reliable data
  group_by(unique_ter_id) %>% 
  summarise(transect = unique(transect), 
            nvisits = n(), 
            sp_name = unique(sp_name), 
            sp_english = unique(sp_english),
            sp_code = unique(sp_code))

nrow(data_terr_tojoin)
# [1] 6515

data_final <- data_centroids %>% 
  left_join(data_terr_tojoin, by = "unique_ter_id")

data_final
nrow(data_final)

plot(st_geometry(data_final))

# st_write(data_final, "./data/territories_centroids_3035.gpkg")
```

### extract environmental covariates 
```{r}
mean_veg_territories <- terra::extract(veg_variables, data_final, fun = mean, na.rm = TRUE)
mean_urban_territoreis <- terra::extract(urban_variables, data_final, fun = mean, na.rm = TRUE)

birds_terr_var <- cbind(data_final, mean_urban_territoreis, mean_veg_territories) %>% 
  dplyr::select(-ID, -ID.1)

summary(birds_terr_var)

tmap_mode("view")
tm_shape(urban_variables) +
  tm_raster("imperv") +
  tm_shape(birds_terr_var) +
  tm_polygons("imperv", alpha = 0.5, border.col = "black")

terr_variables <- birds_terr_var %>% 
  st_drop_geometry()

# write.csv(terr_variables, "./data/territories_environmental_variables.csv", row.names = FALSE)
```


