---
title: "FD_ordination"
author: "Aimara Planillo"
date: "2024-01-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Functional diversity and PCoA


```{r prepare workspace}
source("./rscripts/source_packages.R")
```

### load data
```{r}
## grid data
bird_data <- read.csv("./data/grid_birds_abundance_corrected.csv") %>%
  rename(transect = X) %>% 
  mutate(transect = tolower(transect)) %>% 
  column_to_rownames("transect")
 
ncol(bird_data) #95 species
head(bird_data)

bird_matrix <- as.matrix(bird_data)

## order species alphabetically
bird_matrix2 <- bird_matrix %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("species") %>% 
  arrange(species) %>% 
  column_to_rownames("species") %>% 
  t()


## trait data
birds_traits <- read.csv("data/birds_all_traits.csv") 
head(birds_traits)
birds_traits <- birds_traits %>% 
  arrange(species) %>% 
  filter(!species %in% c("Apus apus", "Passer domesticus")) %>% 
  mutate(migrant_num = as.numeric(migrant_num),
         diet_cat = as.factor(diet_cat))%>%
  dplyr::select(-migrant_cat)

# get species names with underscore
name1 <- stringr::word(birds_traits$species, 1)
name2 <- stringr::word(birds_traits$species, 2)

new_names <- paste(name1,name2, sep = "_")

traits_matrix <- birds_traits %>%
  dplyr::select(-species, -sp_synonym) 
rownames(traits_matrix) <- new_names
```

# Calculate FD indices

```{r}
FD_birds <- FD::dbFD(x = traits_matrix, a = bird_matrix2, 
                     w.abun = TRUE, corr = 'cailliez', 
                     m = 'max', clust.type = 'ward',
                     print.pco = TRUE, calc.FGR = FALSE, ## since we decided we'll focus on FRic, Fdis 
                     stand.FRic = TRUE, calc.FDiv = TRUE)  

FD_birds
saveRDS(FD_birds, "./output/fd_birds.rds")

## weighted mean of functional traits
FD_birds$CWM


mean_traits_transect <- FD_birds$CWM
summary(mean_traits_transect)
table(mean_traits_transect$diet_cat)

# extract diversity values
birds_fr <- FD_birds$FRic 
birds_fe <-FD_birds$FEve
birds_fd <- FD_birds$FDiv


# Add info into one table
birds_fr <-as.data.frame(birds_fr)
birds_fe <-as.data.frame(birds_fe)
birds_fd <-as.data.frame(birds_fd)

row.names(birds_fr)
birds_fr$transect <- rownames(birds_fr)
birds_fe$transect <- rownames(birds_fe)
birds_fd$transect <- rownames(birds_fd)

birds_functional_measures <- left_join(birds_fr, birds_fe,by = "transect")
birds_functional_measures <- left_join(birds_functional_measures, birds_fd, by = "transect")
head(birds_functional_measures)
birds_functional_measures <- birds_functional_measures %>% 
  dplyr::select(transect, everything())

write.csv(birds_functional_measures, "./output/functional_measures_transects.csv", row.names = FALSE)
```


### summaries
```{r}
birds_functional_measures %>% 
  summarise(across(where(is.numeric), list(mean = mean, sd = sd, min = min, max = max)))
```
  birds_fr_mean birds_fr_sd birds_fr_min birds_fr_max birds_fe_mean birds_fe_sd birds_fe_min birds_fe_max birds_fd_mean birds_fd_sd birds_fd_min birds_fd_max
1   0.009612069  0.02091402 2.136223e-09    0.1043922       0.66899   0.0528327    0.5615259    0.7639633     0.8893223  0.02152722     0.852556     0.948475


# PCoA



