---
title: "FD_ordination"
author: "Aimara Planillo"
date: "2024-01-10"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Functional diversity and PCoA


```{r prepare workspace}
source("./rscripts/source_packages.R")
```

### load data
```{r}
## grid data
bird_data <- read.csv("./data/grid_birds_abundance_corrected.csv") %>%
  rename(transect = X) %>% 
  mutate(transect = tolower(transect)) %>% 
  column_to_rownames("transect")
 
ncol(bird_data) #95 species
head(bird_data)

bird_matrix <- as.matrix(bird_data)

## order species alphabetically
bird_matrix2 <- bird_matrix %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("species") %>% 
  arrange(species) %>% 
  column_to_rownames("species") %>% 
  t()


## trait data
birds_traits <- read.csv("data/birds_all_traits.csv") 
head(birds_traits)
birds_traits <- birds_traits %>% 
  arrange(species) %>% 
  filter(!species %in% c("Apus apus", "Passer domesticus")) %>% 
  mutate(migrant_num = as.numeric(migrant_num),
         diet_cat = as.factor(diet_cat))%>%
  dplyr::select(-migrant_cat)

# get species names with underscore
name1 <- stringr::word(birds_traits$species, 1)
name2 <- stringr::word(birds_traits$species, 2)

new_names <- paste(name1,name2, sep = "_")

traits_matrix <- birds_traits %>%
  dplyr::select(-species, -sp_synonym) 
rownames(traits_matrix) <- new_names
```

# 1. Calculate FD indices

```{r}
FD_birds <- FD::dbFD(x = traits_matrix, a = bird_matrix2, 
                     w.abun = TRUE, corr = 'cailliez', 
                     m = 'max', clust.type = 'ward',
                     print.pco = TRUE, calc.FGR = FALSE, ## since we decided we'll focus on FRic, Fdis 
                     stand.FRic = TRUE, calc.FDiv = TRUE)  

FD_birds
# saveRDS(FD_birds, "./output/fd_birds.rds")
# FD_birds <- readRDS("./output/fd_birds.rds")

## weighted mean of functional traits
FD_birds$CWM


mean_traits_transect <- FD_birds$CWM
summary(mean_traits_transect)
table(mean_traits_transect$diet_cat)

# extract diversity values
# Add info into one table
birds_fr <- FD_birds$FRic 
birds_fe <-FD_birds$FEve
birds_fd <- FD_birds$FDiv

birds_fr <-as.data.frame(birds_fr)
birds_fe <-as.data.frame(birds_fe)
birds_fd <-as.data.frame(birds_fd)

row.names(birds_fr)
birds_fr$transect <- rownames(birds_fr)
birds_fe$transect <- rownames(birds_fe)
birds_fd$transect <- rownames(birds_fd)

birds_functional_measures <- left_join(birds_fr, birds_fe,by = "transect")
birds_functional_measures <- left_join(birds_functional_measures, birds_fd, by = "transect")
head(birds_functional_measures)
birds_functional_measures <- birds_functional_measures %>% 
  dplyr::select(transect, everything())

# write.csv(birds_functional_measures, "./output/functional_measures_transects.csv", row.names = FALSE)
# birds_functional_measures <- read.csv("./output/functional_measures_transects.csv")
```


### summaries
```{r}
birds_functional_measures %>% 
  summarise(across(where(is.numeric), list(mean = mean, sd = sd, min = min, max = max)))
```


# 2. PCoA

```{r load data}
## bird abund transect
bird_abund <- bird_data %>% 
  rownames_to_column("transect")

## trait data transect
mean_traits_transect <- FD_birds$CWM %>% 
  rownames_to_column("transect")

## env covariates grid
covariates_grid <- read.csv("./data/grids_environmental_variables.csv") 

## env covariates territory
covariates_terr <- read.csv("./data/territories_environmental_variables.csv") 

## env covariates points
covariates_pts <- read.csv("./data/locations_environmental_variables_20m.csv") 
```



## 2.1 PCoA grid scale 

### prepare data for grid scale 
```{r}
## merge together to make sure the order is correct
all_data_grid <- bird_abund %>% 
  left_join(covariates_grid, by = "transect") %>% 
  left_join(mean_traits_transect, by = "transect") %>% 
  column_to_rownames("transect")

nrow(all_data_grid)
# [1] 29 sites
ncol(all_data_grid)
# [1] 112 # 95 species abundances, 2 coordinates, 10 env variables and 5 and mean trait values

head(all_data_grid)
## divide into the proper tables
species_matrix <- all_data_grid %>% 
  dplyr::select(Accipiter_gentilis:Turdus_philomelos)
env_matrix <- all_data_grid %>% 
  dplyr::select(pop_den:glcm_hmg)
traits_matrix <- all_data_grid %>% 
  dplyr::select(log_bodymass:diet_cat)

str(species_matrix)
str(env_matrix)
str(traits_matrix)
```


### Run ordination
```{r}
## species ordination
PCoA_communitycomposition <- capscale(species_matrix ~ 1, dist="bray", metaMDS = TRUE)

## add environmetal variables
ef <- envfit(PCoA_communitycomposition, env_matrix, permu = 999, na.rm = T)
ef

## Add traits 
tq <- envfit(PCoA_communitycomposition, traits_matrix, permu = 999)

# Add species 
spf <- envfit(PCoA_communitycomposition, species_matrix, permu = 999)
spf

# plot(PCoA_communitycomposition, type = "t", display = "sites")
# plot(ef, cex = 0.7)
# plot(tq, cex = 0.6, col = "darkgreen")
# plot(spf, col = "red")
```

```{r extract data for plotting}
spf$vectors$arrows
spf$vectors$pvals

sign_sp <- names(spf$vectors$pvals[spf$vectors$pvals < 0.05]) # get names of the significant sp

species_scores <- spf$vectors$arrows %>%
  as.data.frame() %>%
  rownames_to_column("species") 
species_scores <- filter(species_scores, species %in% sign_sp)

# get sites loads in axis
site_scores <- as.data.frame(scores(PCoA_communitycomposition)$sites)

# get coordinates of environmental variables
env_coord_cont <- as.data.frame(scores(ef, "vectors")) * ordiArrowMul(ef)
env_variables <- c("pop_den", "imperv", "tcd", "light", "noise", "veg_pca1", "veg_pca2", "ndvi", "glcm", "glcm_hmg")
rownames(env_coord_cont) <- env_variables

# remove ndvi because overlaps almost perfectly with glcm
env_coord_cont <- env_coord_cont[-8,] 

# get coordinates of traits 
traits_coord_cat <- as.data.frame(scores(tq, "factors"))
rownames(traits_coord_cat) <- c("Invertebrates", "Omnivore")
traits_coord_cat

traits_coord_cont <- as.data.frame(scores(tq, "vectors")) * ordiArrowMul(tq)
rownames(traits_coord_cont) <- c("Migrant", "BodyMass", "Longevity", "Clutch_size")
traits_coord_cont
```

```{r ggplot}
## plot in ggplot
(myplot_grid <- ggplot(data = site_scores, aes(x = MDS1, y = MDS2)) + 
  geom_point(colour = "orange", size = 5, alpha = 0.3) + 
  # scale_colour_manual(values = c( "orange")) + 
  geom_segment(data = env_coord_cont, aes(x = 0, y = 0, xend = MDS1, yend = MDS2), 
               linewidth = 1, alpha = 0.5, colour = "darkgreen", 
               arrow = arrow(length = unit(0.3,"cm"))) +
  geom_text(data = env_coord_cont, aes(x = MDS1*1.2, y = MDS2*1.2),size = 4, colour = "darkgreen", 
            fontface = "bold", label = row.names(env_coord_cont)) + 
  geom_segment(data = traits_coord_cat, aes(x = 0, y = 0, xend = MDS1, yend = MDS2), 
               linewidth = 1, alpha = 0.5, colour = "black", 
               arrow = arrow(length = unit(0.3,"cm"))) +
  geom_text(data = traits_coord_cat, aes(x = MDS1*1.2, y = MDS2*1.2),size = 4,  colour = "black", 
            fontface = "bold", label = row.names(traits_coord_cat)) + 
  geom_segment(data = traits_coord_cont, aes(x = 0, y = 0, xend = MDS1, yend = MDS2), 
               linewidth = 1, alpha = 0.5, colour = "black", 
               arrow = arrow(length = unit(0.3,"cm"))) +
  geom_text(data = traits_coord_cont, aes(x = MDS1*1.2, y = MDS2*1.2),size = 4,  colour = "black", 
            fontface = "bold", label = row.names(traits_coord_cont)) + 
  geom_hline(yintercept = 0, col = "grey70", lty = 4) +
  geom_vline(xintercept = 0, col = "grey70", lty = 4) +
  xlim(c(-1.8,1.8)) +
  ylim(c(-1.5,1.5)) +
  ggtitle("Grid scale - All birds") +
  theme(axis.title = element_text(size = 14, face = "bold", colour = "black"), 
       panel.background = element_blank(), 
       panel.border = element_rect(fill = NA, colour = "black"), 
       axis.text = element_text(size = 14, colour = "black")))

# ggsave(plot = myplot_grid, 
#        filename = "./plots/PCoA_grid_scale.png", 
#        dpi = 900, height = 8, width = 8)
# saveRDS(myplot_grid, "./output/PCoAplot_grid_allbirds.rds")
```

# 2.2 PCoA territory scale


### prepare data for territory scale 
```{r}
covariates_terr_mean <- covariates_terr %>% 
  dplyr::select(-nvisits) %>% 
  group_by(transect) %>% 
  summarise(across(where(is.numeric), list(mean = ~mean(., na.rm = TRUE))))

## merge together to make sure the order is correct
all_data_terr <- bird_abund %>% 
  left_join(covariates_terr_mean, by = "transect") %>% 
  left_join(mean_traits_transect, by = "transect") %>% 
  column_to_rownames("transect")

nrow(all_data_terr)
# [1] 29 sites
ncol(all_data_terr)
# [1] 110 # 95 species abundances, 10 env variables and 5 and mean trait values

## divide into the proper tables
species_matrix_terr <- all_data_terr %>% 
  dplyr::select(Accipiter_gentilis:Turdus_philomelos)
env_matrix_terr <- all_data_terr %>% 
    dplyr::select(pop_den_mean:glcm_hmg_mean)
traits_matrix_terr <-all_data_terr %>% 
    dplyr::select(log_bodymass:diet_cat)

str(species_matrix_terr)
str(env_matrix_terr)
str(traits_matrix_terr)
```


```{r PCoA territories - bird community composition}
# Run PCoa of sites based on community compositon (species abundances)
PCoA_terr <- capscale(species_matrix_terr ~ 1, dist="bray", metaMDS = TRUE)

# Add environmental variables
ef_terr <- envfit(PCoA_terr, env_matrix_terr, permu = 999, na.rm = T)

# Add traits per quadrant
tq_terr <- envfit(PCoA_terr, traits_matrix_terr, permu = 999)

# Add species
spf_terr <- envfit(PCoA_terr, species_matrix_terr, permu = 999)

# # Get significant species loads in the axes
spf_terr$vectors$arrows
spf_terr$vectors$pvals

sign_sp_terr <- names(spf_terr$vectors$pvals[spf_terr$vectors$pvals < 0.05]) # get names of the significant sp

species_scores_terr <- spf_terr$vectors$arrows %>%
  as.data.frame() %>%
  rownames_to_column("species") 
species_scores_terr <- filter(species_scores_terr, species %in% sign_sp_terr)

# get sites loads in axis
site_scores_terr <- as.data.frame(scores(PCoA_terr)$sites)

# get coordinates of environmental variables
env_coord_cont_terr <- as.data.frame(scores(ef_terr, "vectors")) * ordiArrowMul(ef_terr)

env_variables <- c("pop_den", "imperv", "tcd", "light", "noise", "veg_pca1", "veg_pca2", "ndvi", "glcm", "glcm_hmg")
rownames(env_coord_cont_terr) <- env_variables

# remove ndvi because overlaps almost perfectly with glcm
env_coord_cont_terr <- env_coord_cont_terr[-8,] 

# get coordinates of traits 
traits_coord_cat_terr <- as.data.frame(scores(tq_terr, "factors"))
rownames(traits_coord_cat_terr) <- c("Invertebrates", "Omnivore")
traits_coord_cat_terr

traits_coord_cont_terr <- as.data.frame(scores(tq_terr, "vectors")) * ordiArrowMul(tq_terr)
rownames(traits_coord_cont_terr) <- c("Migrant", "BodyMass", "Longevity", "Clutch_size")
traits_coord_cont_terr
```

```{r plot PCoA - territories}
(myplot_terr <- ggplot(data = site_scores_terr, aes(x = MDS1, y = MDS2)) + 
  geom_point(colour = "orange", size = 5, alpha = 0.3) + 
  # scale_colour_manual(values = c( "orange")) + 
  geom_segment(data = env_coord_cont_terr, aes(x = 0, y = 0, xend = MDS1, yend = MDS2), 
               linewidth = 1, alpha = 0.5, colour = "darkgreen", 
               arrow = arrow(length = unit(0.3,"cm"))) +
  geom_text(data = env_coord_cont_terr, aes(x = MDS1*1.2, y = MDS2*1.2),size = 4, colour = "darkgreen", 
            fontface = "bold", label = row.names(env_coord_cont_terr)) + 
  geom_segment(data = traits_coord_cat_terr, aes(x = 0, y = 0, xend = MDS1, yend = MDS2), 
               linewidth = 1, alpha = 0.5, colour = "black", 
               arrow = arrow(length = unit(0.3,"cm"))) +
  geom_text(data = traits_coord_cat_terr, aes(x = MDS1*1.2, y = MDS2*1.2),size = 4,  colour = "black", 
            fontface = "bold", label = row.names(traits_coord_cat_terr)) + 
  geom_segment(data = traits_coord_cont_terr, aes(x = 0, y = 0, xend = MDS1, yend = MDS2), 
               linewidth = 1, alpha = 0.5, colour = "black", 
               arrow = arrow(length = unit(0.3,"cm"))) +
  geom_text(data = traits_coord_cont_terr, aes(x = MDS1*1.2, y = MDS2*1.2),size = 4,  colour = "black", 
            fontface = "bold", label = row.names(traits_coord_cont_terr)) + 
  geom_hline(yintercept = 0, col = "grey70", lty = 4) +
  geom_vline(xintercept = 0, col = "grey70", lty = 4) +
  xlim(c(-1.8,1.8)) +
  ylim(c(-1.5,1.5)) +
  ggtitle("Territory scale - All birds") +
  theme(axis.title = element_text(size = 14, face = "bold", colour = "black"), 
       panel.background = element_blank(), 
       panel.border = element_rect(fill = NA, colour = "black"), 
       axis.text = element_text(size = 14, colour = "black")))

# ggsave(plot = myplot_terr, 
#        filename = "./plots/PCoA_territory_scale.png", 
#        dpi = 900, height = 8, width = 8)
# saveRDS(myplot_terr, "./output/PCoAplot_terr_allbirds.rds")
```


# 2.3 PCoA Location Points scale

```{r}
covariates_pts_mean <- covariates_pts %>% 
  dplyr::select(-visit) %>% 
  group_by(transect) %>% 
  summarise(across(where(is.numeric), list(mean = ~mean(., na.rm = TRUE))))

## merge together to make sure the order is correct
all_data_pts <- bird_abund %>% 
  left_join(covariates_pts_mean, by = "transect") %>% 
  left_join(mean_traits_transect, by = "transect") %>% 
  column_to_rownames("transect")

nrow(all_data_pts)
# [1] 29 sites
ncol(all_data_pts)
# [1] 110 # 95 species abundances, 10 env variables and 5 and mean trait values

## divide into the proper tables
species_matrix_pts <- all_data_pts %>% 
  dplyr::select(Accipiter_gentilis:Turdus_philomelos)
env_matrix_pts <- all_data_pts %>% 
    dplyr::select(pop_den_mean:glcm_hmg_mean)
traits_matrix_pts <-all_data_pts %>% 
    dplyr::select(log_bodymass:diet_cat)

str(species_matrix_pts)
str(env_matrix_pts)
str(traits_matrix_pts)
```

### Run ordination
```{r}
## species ordination
PCoA_communitycomposition <- capscale(species_matrix_pts ~ 1, dist="bray", metaMDS = TRUE)

## add environmetal variables
ef <- envfit(PCoA_communitycomposition, env_matrix_pts, permu = 999, na.rm = T)
ef

## Add traits 
tq <- envfit(PCoA_communitycomposition, traits_matrix_pts, permu = 999)

# Add species 
spf <- envfit(PCoA_communitycomposition, species_matrix_pts, permu = 999)
spf
```

```{r extract data for plotting}
spf$vectors$arrows
spf$vectors$pvals

sign_sp <- names(spf$vectors$pvals[spf$vectors$pvals < 0.05]) # get names of the significant sp

species_scores <- spf$vectors$arrows %>%
  as.data.frame() %>%
  rownames_to_column("species") 
species_scores <- filter(species_scores, species %in% sign_sp)

# get sites loads in axis
site_scores <- as.data.frame(scores(PCoA_communitycomposition)$sites)
# site_scores <- read.csv("Book2.csv", row.names = 1)

# get coordinates of environmental variables
env_coord_cont <- as.data.frame(scores(ef, "vectors")) * ordiArrowMul(ef)
env_variables <- c("pop_den", "imperv", "tcd", "light", "noise", "veg_pca1", "veg_pca2", "ndvi", "glcm", "glcm_hmg")
rownames(env_coord_cont) <- env_variables

# remove ndvi because overlaps almost perfectly with glcm
env_coord_cont <- env_coord_cont[-8,] 

# get coordinates of traits 
traits_coord_cat <- as.data.frame(scores(tq, "factors"))
rownames(traits_coord_cat) <- c("Invertebrates", "Omnivore")
traits_coord_cat

traits_coord_cont <- as.data.frame(scores(tq, "vectors")) * ordiArrowMul(tq)
rownames(traits_coord_cont) <- c("Migrant", "BodyMass", "Longevity", "Clutch_size")
traits_coord_cont
```

```{r ggplot}
## plot in ggplot
(myplot_pts <- ggplot(data = site_scores, aes(x = MDS1, y = MDS2)) + 
  geom_point(colour = "orange", size = 5, alpha = 0.3) + 
  # scale_colour_manual(values = c( "orange")) + 
  geom_segment(data = env_coord_cont, aes(x = 0, y = 0, xend = MDS1, yend = MDS2), 
               linewidth = 1, alpha = 0.5, colour = "darkgreen", 
               arrow = arrow(length = unit(0.3,"cm"))) +
  geom_text(data = env_coord_cont, aes(x = MDS1*1.2, y = MDS2*1.2),size = 4, colour = "darkgreen", 
            fontface = "bold", label = row.names(env_coord_cont)) + 
  geom_segment(data = traits_coord_cat, aes(x = 0, y = 0, xend = MDS1, yend = MDS2), 
               linewidth = 1, alpha = 0.5, colour = "black", 
               arrow = arrow(length = unit(0.3,"cm"))) +
  geom_text(data = traits_coord_cat, aes(x = MDS1*1.2, y = MDS2*1.2),size = 4,  colour = "black", 
            fontface = "bold", label = row.names(traits_coord_cat)) + 
  geom_segment(data = traits_coord_cont, aes(x = 0, y = 0, xend = MDS1, yend = MDS2), 
               linewidth = 1, alpha = 0.5, colour = "black", 
               arrow = arrow(length = unit(0.3,"cm"))) +
  geom_text(data = traits_coord_cont, aes(x = MDS1*1.2, y = MDS2*1.2),size = 4,  colour = "black", 
            fontface = "bold", label = row.names(traits_coord_cont)) + 
  geom_hline(yintercept = 0, col = "grey70", lty = 4) +
  geom_vline(xintercept = 0, col = "grey70", lty = 4) +
  xlim(c(-1.8,1.8)) +
  ylim(c(-1.5,1.5)) +
  ggtitle("Point scale - All birds") +
  theme(axis.title = element_text(size = 14, face = "bold", colour = "black"), 
       panel.background = element_blank(), 
       panel.border = element_rect(fill = NA, colour = "black"), 
       axis.text = element_text(size = 14, colour = "black")))

# ggsave(plot = myplot_pts, 
#        filename = "./plots/PCoA_points_scale.png", 
#        dpi = 900, height = 8, width = 8)
# saveRDS(myplot_pts, "./output/PCoAplot_pts_allbirds.rds")
```


## Put all plots together
```{r load data}
library(patchwork)

myplot_grid <- readRDS("./output/PCoAplot_grid_allbirds.rds")
myplot_terr <- readRDS("./output/PCoAplot_terr_allbirds.rds")
myplot_pts <- readRDS("./output/PCoAplot_pts_allbirds.rds")
```


```{r prepare plot layout}
## get plots without titles
plot_grid <- myplot_grid + ggtitle(NULL) +
  labs(tag = "A") +
  xlab("MDS1") +
  ylab("MDS2") +
  theme(plot.tag = element_text(hjust = 0, size = 14, vjust = 0, face = "bold"),
    plot.tag.position = c(0.13, 0.95))

plot_terr <- myplot_terr + ggtitle(NULL) +
  labs(tag = "B") +
  xlab("MDS1") +
  ylab("MDS2") +
  theme(plot.tag = element_text(hjust = 0, size = 14, vjust = 0, face = "bold"),
    plot.tag.position = c(0.09, 0.95))

plot_pts <- myplot_pts + ggtitle(NULL) +
  labs(tag = "C") +
  xlab("MDS1") +
  ylab("MDS2") +
  theme(plot.tag = element_text(hjust = 0, size = 14, vjust = 0, face = "bold"),
    plot.tag.position = c(0.09, 0.95))


## get row names
col1 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Grid Scale", size = 8) + theme_void() 
col2 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Territory Scale", size = 8) + theme_void() 
col3 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Point Scale", , size = 8) + theme_void() 
row1 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="All birds", angle = 90, , size = 8) + theme_void() 

## define layout 
layoutplot <- "
#aaabbbccc
dggghhhiii
dggghhhiii
"

plotlist <- list(a = col1, b = col2, c = col3,
                 d = row1, 
                 g = plot_grid, h = plot_terr, i = plot_pts)

wrap_plots(plotlist, guides = 'collect', design = layoutplot) +
  plot_layout(axis_titles = "collect", heights = c(1, 0.5 , 3)) 
  # plot_annotation(tag_levels = 'A') 
  
ggsave(filename = "./plots/PCoA_allplots_allbirds.png", 
        dpi = 900, height = 6, width = 16)
```


## Plot grid + point scale

```{r prepare grid point layout}
## get plots without titles
plot_grid <- myplot_grid + ggtitle(NULL) +
  labs(tag = "A") +
  xlab("MDS1") +
  ylab("MDS2") +
  theme(plot.tag = element_text(hjust = 0, size = 14, vjust = 0, face = "bold"),
    plot.tag.position = c(0.15, 0.95))

plot_pts <- myplot_pts + ggtitle(NULL) +
  labs(tag = "B") +
  xlab("MDS1") +
  ylab("MDS2") +
  theme(plot.tag = element_text(hjust = 0, size = 14, vjust = 0, face = "bold"),
    plot.tag.position = c(0.09, 0.95))


## get row names
col1 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Grid Scale", size = 8) + theme_void() 
col3 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Point Scale", , size = 8) + theme_void() 

## define layout 
layoutplot <- "
aaaccc
gggiii
gggiii
"

plotlist <- list(a = col1, c = col3,
                 g = plot_grid, i = plot_pts)

wrap_plots(plotlist, guides = 'collect', design = layoutplot) +
  plot_layout(axis_titles = "collect", heights = c(1, 0.5 , 3)) 
  # plot_annotation(tag_levels = 'A') 
  
ggsave(filename = "./plots/PCoA_2scales_allbirds.png", 
        dpi = 900, height = 6, width = 10)
```
